import { Box, Container, Heading } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import backImg from "../public/images/backimage.png";
import UploadButton from "../components/UploadButton";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        mx="auto"
        minWidth="500px"
        maxWidth="700px"
        bgRepeat="no-repeat"
      >
        <Image src="/backimage.png" layout="fill" objectFit="cover" />

        <Heading as="h1" size="2xl" isTruncated>
          🔥Remote Worker Checker🔥
        </Heading>

        <Container py={2}>
          <Box
            minHeight="100vh"
            px={1}
            display="flex"
            flex={1}
            flexDirection="column"
            justifyContent="center"
            alignItems="center"
          >
            <p className={styles.description}>
              あなたのリモートオフィスからリモートワーカー度を計測します
            </p>

            <UploadButton />

            <code className={styles.code}>
              const Remote Worker Level = objectRecognition(remoteOffice);
            </code>

            <div className={styles.grid}>
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>Documentation &rarr;</h2>
                <p>Find in-depth information about Next.js features and API.</p>
              </a>
              <a
                href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                className={styles.card}
              >
                <h2>Deploy &rarr;</h2>
                <p>
                  Instantly deploy your Next.js site to a public URL with
                  Vercel.
                </p>
              </a>
            </div>
          </Box>

          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{" "}
              <span className={styles.logo}>
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={72}
                  height={16}
                />
              </span>
            </a>
          </footer>
        </Container>
      </Container>
    </>
  );
};

export default Home;
