import Head from "next/head";
import Image from "next/image";
import type { NextPage } from "next";
import React from "react";

import { Box, Code, Container, Heading, Text } from "@chakra-ui/react";

import styles from "../styles/Home.module.css";
import UploadButton from "../components/UploadButton";
import ResultChart from "../components/ResultChart";

const Home: NextPage = () => {
  const [IsDetected, setIsDetected] = React.useState<Boolean>(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        pos="fixed"
        h="100vh"
        w="100vw"
        opacity={0.35}
        overflow="hidden"
        zIndex={-1}
      >
        <Image
          alt="Mountains"
          src="/backimage.png"
          layout="fill"
          objectFit="cover"
          quality={100}
        />
      </Box>

      <Container mx="auto" width="100%" bgRepeat="no-repeat">
        <Heading
          py={5}
          as="h1"
          size="xl"
          isTruncated
          textAlign="center"
          pt="10vh"
        >
          Remote Work Checker
        </Heading>
        <Container py={2}>
          <Box
            px={1}
            display="flex"
            flex={1}
            flexDirection="column"
            justifyContent="center"
            alignItems="center"
          >
            <Text fontSize="md" pt={3} pb={5}>
              あなたのリモートオフィスからリモートワーカー度を計測
            </Text>

            <Code>
              const Remote Worker Level = objectRecognition(remoteOffice_path);
            </Code>

            <UploadButton
              IsDetected={IsDetected}
              setIsDetected={setIsDetected}
            />

            {IsDetected ? (
              <>
                <ResultChart />
              </>
            ) : (
              <></>
            )}
          </Box>

          <footer className={styles.footer}>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{" "}
              <span className={styles.logo}>
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={72}
                  height={16}
                />
              </span>
            </a>
          </footer>
        </Container>
      </Container>
    </>
  );
};

export default Home;
